# Generated by Django 4.1.2 on 2022-10-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
