# Generated by Django 4.1.2 on 2022-10-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0002_alter_resturant_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturant',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
